// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWI7arQ41fHDTfKHCEIeoLiVin6NBZXNY',
    appId: '1:325798970573:web:d5376e6db51eaac840d584',
    messagingSenderId: '325798970573',
    projectId: 'diabetes-a33a3',
    authDomain: 'diabetes-a33a3.firebaseapp.com',
    storageBucket: 'diabetes-a33a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6Q4nQyPoK3qXbeOVZ3OP4QSrrqLVvZE',
    appId: '1:325798970573:android:c88404d571da839040d584',
    messagingSenderId: '325798970573',
    projectId: 'diabetes-a33a3',
    storageBucket: 'diabetes-a33a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRN3F9txXpr-ai8NioiuUXlL34DXlJhQ',
    appId: '1:325798970573:ios:b49ad9e986ae8de240d584',
    messagingSenderId: '325798970573',
    projectId: 'diabetes-a33a3',
    storageBucket: 'diabetes-a33a3.appspot.com',
    iosBundleId: 'com.example.diabetes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRN3F9txXpr-ai8NioiuUXlL34DXlJhQ',
    appId: '1:325798970573:ios:b49ad9e986ae8de240d584',
    messagingSenderId: '325798970573',
    projectId: 'diabetes-a33a3',
    storageBucket: 'diabetes-a33a3.appspot.com',
    iosBundleId: 'com.example.diabetes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWI7arQ41fHDTfKHCEIeoLiVin6NBZXNY',
    appId: '1:325798970573:web:e7823b09fa81f92740d584',
    messagingSenderId: '325798970573',
    projectId: 'diabetes-a33a3',
    authDomain: 'diabetes-a33a3.firebaseapp.com',
    storageBucket: 'diabetes-a33a3.appspot.com',
  );
}
